add_rest_api
GraphLabsSuite/Web pull request #14
Opened 2017-11-03 20:07 UTC by avalsa

Реализован переход на функционал с использованием REST-API

2017-11-05 09:07 UTC, svtz requested changes

2017-11-05 09:07 UTC, svtz commented on GraphLabs.WcfServices/Web.Base.config
> +    <add key="IsDebug" value="true" />
вот это выставлять нужно только в web.debug.config, здесь нужно вернуть как было

2017-11-05 09:07 UTC, svtz commented on GraphLabs.WcfServices/Web.Base.config
> +      <service name="GraphLabs.WcfServices.Service2">
что такое Service2??

2017-11-05 09:07 UTC, svtz commented on GraphLabs.WcfServices/Web.Base.config
> +                  bindingConfiguration="Basic" name="Basic" bindingNamespace="http://dszss.proitr.ru/WCF"
хотя бы http://dszss.proitr.ru/WCF убери =)
я понимаю, что копипаста, но credits в таких случаях оставляют в виде комментов =)

2017-11-05 19:39 UTC, avalsa commented on GraphLabs.WcfServices/Web.Base.config
> +    <add key="IsDebug" value="true" />
ок

2017-11-05 19:39 UTC, avalsa commented on GraphLabs.WcfServices/Web.Base.config
> +      <service name="GraphLabs.WcfServices.Service2">
ок

2017-11-05 19:40 UTC, avalsa commented on GraphLabs.WcfServices/Web.Base.config
> +                  bindingConfiguration="Basic" name="Basic" bindingNamespace="http://dszss.proitr.ru/WCF"
)))

2017-11-05 19:45 UTC, avalsa commented
исправлено

2017-12-09 08:18 UTC, svtz approved these changes

2017-12-09 08:18 UTC, merged