Start page
GraphLabsSuite/Web pull request #15
Opened 2017-12-09 15:09 UTC by Karkh-Elizaveta

Изменено меню, в header добавлена строка поиска, создана стартовая страница("Личный кабинет") с расписанием.
На стартовой странице - отображение расписания выбранной недели, возможность переключения между неделями, возможность возврата к текущей календарной неделе.

2017-12-11 05:41 UTC, svtz requested changes
Пока замечания чисто косметические.

2017-12-11 05:41 UTC, svtz commented on GraphLabs.Site.Models/Schedule/LabScheduleListModel.cs
> +    public interface IFilterableByDate<TListModel, TModel>
Нужно вынести в отдельный файл

2017-12-11 05:41 UTC, svtz commented on GraphLabs.Site/Content/Grids.css
> +.grid {
Есть мнение, что этот файл лишний, т.к. есть такой-же-но-другой Content/css/Grids.css
Надо аккуратно посмотреть, который из них на самом деле используется, а лишний - удалить.

2017-12-11 05:41 UTC, svtz commented on GraphLabs.Site/Controllers/StartpageController.cs
> +                 .FilterByDate(ourdate.AddDays((DayOfWeek.Monday - ourdate.DayOfWeek) * (ourdate.DayOfWeek - ourdate.AddDays(-1).DayOfWeek)),
условие смотрится жестко, но т.к. пока всё равно календарные недели - оставляем как есть.

2017-12-11 05:41 UTC, svtz commented on GraphLabs.Site/GraphLabs.Site.csproj
> +    <Content Include="Content\Grids.css" />
здесь тоже Grids.css

2017-12-11 05:41 UTC, svtz commented on GraphLabs.Site/Views/Shared/_Layout.cshtml
> +                <!--<section class="@(MenuIsVisible() ? "main-content-with-menu" : "main-content-without-menu")">-->
Комментированный код НЕЕЕЕТ =)

2017-12-11 06:20 UTC, Karkh-Elizaveta commented on GraphLabs.Site/Content/Grids.css
> +.grid {
Починила

2017-12-12 16:22 UTC, Karkh-Elizaveta commented
Вид Startpage: не работают ссылки "Добавить работу..."

2018-03-03 05:44 UTC, svtz approved these changes

2018-03-03 06:18 UTC, merged