AbstractRemover + добавление/удаление пустого тестпула
GraphLabsSuite/Web pull request #4
Opened 2017-03-13 12:38 UTC by eakarpov

Добавлен интерфейс работы с репозиторием для удаления объекта сущности.

Добавлены новые загрузчики, "удалятели", сейверы для TestPool и TestPoolEntry.

Добавлен контроллер TestPoolEntry, куда вынесены функции для обработки запросов на TestPoolEntry.

Добился успешного добавления и удаления пустого тестпула. Добавление/Удаление элементов в тестпул пока не работает.

2017-03-13 17:01 UTC, svtz requested changes
Нужно разбираться, почему не работает передача моделей в методы TestPoolController, т.к. получившиеся там приседания - это, конечно, жесть.

И просьба не пуллреквестить закоментированный код. На худой случай комменты //todo здесь то-то

2017-03-13 17:01 UTC, svtz commented on GraphLabs.DomainModel/TestPool.cs
> +
Вот такие правки лучше ревертить перед коммитом :)
Сейчас уж пусть остаётся.

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +    abstract class AbstractModelRemover<TModel, TEntity> : IEntityBasedModelRemover<TModel, TEntity>
лучше явно указать спецификатор доступа. В данном случае, скорее всего, `internal`

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +        protected virtual Type GetEntityType(TModel model)
кажется, этот метод нужно заинлайнить

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                var flag = false;
:triangular_flag_on_post:- не самое удачное имя для переменной 
и вообще, там, где сейчас флагу присваивается true/false - можно сразу делать return успех/провал

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                    catch (Exception e)
вот так глотать исключения очень-очень плохо (можно поймать например OutOfMemory, и как ни в чём не бывало продолжить работу).
Нужно узнать конкретный тип исключения, который тут выбрасывается в случае нарушения ограничения целостности, и перехватывать только его

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                    var type = GetEntityType(model);
А эта переменная вообще используется?

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +        DeletionStatus Remove(TModel model);
Смущает, что `DeletionStatus`, но при этом интерфейс `*Remover`, и метод `Remove`

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +    class TestPoolModelRemover : AbstractModelRemover<TestPoolModel, DomainModel.TestPool>
`internal sealed`

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelLoader.cs
>      class TestPoolModelLoader : AbstractModelLoader<TestPoolModel, DomainModel.TestPool>
`internal sealed`

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +                g.LabVariants = model.LabVariants;
очень смущает наличие отсюда ссылки на лаб варианты

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelLoader.cs
> +    class TestPoolEntryModelLoader : AbstractModelLoader<TestPoolEntryModel, DomainModel.TestPoolEntry>
`internal sealed`

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelRemover.cs
> +    class TestPoolEntryModelRemover : AbstractModelRemover<TestPoolEntryModel, DomainModel.TestPoolEntry>
`internal sealed`

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelSaver.cs
> +    class TestPoolEntryModelSaver : AbstractModelSaver<TestPoolEntryModel, DomainModel.TestPoolEntry>
отгадай

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                        var m = operation.DataContext.Query.Get<TEntity>(GetEntityKey(model));
mммм?

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +            var m = query.Get<DomainModel.TestPool>(model.Id);
mммм?

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
>      class TestPoolModelSaver : AbstractModelSaver<TestPoolModel, DomainModel.TestPool>
`internal sealed`

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            TestPool res = _modelSaver.CreateOrUpdate(testPool);
Это как раз тот случай, где тебе TestPool не приходил в метод?
Вообще выглядит крайне странно. Что там за Id такой, что лоадер его загружает?

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            TestPool res = _modelSaver.CreateOrUpdate(testPool);
и тут те же странные приседания

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            var result = _modelRemover.Remove(testPool);
не, определённо нужно учиться получать в методы модели. Так не пойдёт.

2017-03-13 17:01 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +            var testPoolEntry = new TestPoolEntryModel();
а это зачем? почему не лоадер это делает?

2017-03-13 17:41 UTC, eakarpov commented on GraphLabs.DomainModel/TestPool.cs
> +
Да, это лажанул явно(

2017-03-13 18:00 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +    abstract class AbstractModelRemover<TModel, TEntity> : IEntityBasedModelRemover<TModel, TEntity>
Сменено

2017-03-13 18:12 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
>      class TestPoolModelSaver : AbstractModelSaver<TestPoolModel, DomainModel.TestPool>
Сделано

2017-03-13 18:14 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelRemover.cs
> +    class TestPoolEntryModelRemover : AbstractModelRemover<TestPoolEntryModel, DomainModel.TestPoolEntry>
Сделано

2017-03-13 18:14 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelLoader.cs
> +    class TestPoolEntryModelLoader : AbstractModelLoader<TestPoolEntryModel, DomainModel.TestPoolEntry>
Сделано

2017-03-13 18:14 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelLoader.cs
>      class TestPoolModelLoader : AbstractModelLoader<TestPoolModel, DomainModel.TestPool>
Сделано

2017-03-13 18:14 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelSaver.cs
> +    class TestPoolEntryModelSaver : AbstractModelSaver<TestPoolEntryModel, DomainModel.TestPoolEntry>
Сделано

2017-03-13 18:16 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +        protected virtual Type GetEntityType(TModel model)
Сделано.

2017-03-13 18:18 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                    var type = GetEntityType(model);
Если про type, то я её убрал.

2017-03-13 18:19 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                        var m = operation.DataContext.Query.Get<TEntity>(GetEntityKey(model));
Убрал переменную m, внёс её значение в следующую строчку.

2017-03-13 18:21 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +        DeletionStatus Remove(TModel model);
Изменил на RemovalStatus

2017-03-13 18:21 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +    class TestPoolModelRemover : AbstractModelRemover<TestPoolModel, DomainModel.TestPool>
Сделано

2017-03-13 18:22 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +            var m = query.Get<DomainModel.TestPool>(model.Id);
Изменил на entity

2017-03-13 18:23 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +                g.LabVariants = model.LabVariants;
Ну модель была эквивалентна сущности. Теперь раз одно я уже убрал, думаю можно убрать и варианты лаб... Ок.

2017-03-13 18:28 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                    catch (Exception e)
Изменил на SqlException. Нормально?

2017-03-13 18:29 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                var flag = false;
Не уверен, что можно сделать ретерн сразу в этой функции... Изменил имя на isSuccessfullyRemoved

2017-03-13 18:36 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +            var testPoolEntry = new TestPoolEntryModel();
Этой же модели ещё нету в базе данных. Разве не надо создать модель, а потом её CreateOrUpdate сделать?

2017-03-13 18:48 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            TestPool res = _modelSaver.CreateOrUpdate(testPool);
Id модели TestPool...

2017-03-14 04:23 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +            var testPoolEntry = new TestPoolEntryModel();
это же Index, он ничего не может создавать.

2017-03-14 04:51 UTC, svtz requested changes

2017-03-14 04:51 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                        isSuccessfullyRemoved = true;
здесь можно сразу return Success

2017-03-14 04:51 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
>                      }
здесь желательно ещё проверить, что e.ErrorCode равен ожидаемому. После чего сделать return SomeFKExistOnTheElement. А если не равен, но UnknownFailure

2017-03-14 04:51 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
>          protected override Action<DomainModel.TestPool> GetEntityInitializer(TestPoolModel model, IEntityQuery query)
есть чёткое ощущение, что этот метод не нужен. Зачем инициализировать модель для её удаления?
Нужно удалить и отсюда, и из базового класса.

2017-03-14 04:51 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolController.cs
>                  ViewBag.Message = "The test pool has been successfully deleted!";
давайте уж на русском сообщения выводить!

2017-03-14 04:51 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
> +                g.TestPoolEntries = entity.TestPoolEntries;
Идея этого метода - проинициализировать _изменившиеся_ поля сущности, чтобы потом сохранить эти изменения в БД.
Таким образом, вычитывать сущность из базы и присваивать коллекции LabVariants и TestPoolEntries не нужно, если ты их не изменяешь.
Если посмотреть использования этого метода в базовом классе, можно увидеть, что там это уже делается.

2017-03-14 06:36 UTC, svtz commented
[Картинка](https://drive.google.com/file/d/0B-tGET5p4UoRRm1oeTRFTWh5T0E/view?usp=sharing)

2017-03-14 06:36 UTC, svtz commented
Прикладываю [картинку](https://drive.google.com/file/d/0B-tGET5p4UoRRm1oeTRFTWh5T0E/view?usp=sharing)

2017-03-14 08:00 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolController.cs
>                  ViewBag.Message = "The test pool has been successfully deleted!";
Согласен, плохая привычка.. Изменю.

2017-03-14 08:09 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolController.cs
>                  ViewBag.Message = "The test pool has been successfully deleted!";
Изменил

2017-03-14 08:11 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
> +                g.TestPoolEntries = entity.TestPoolEntries;
Удалил присваивание LabVariants. Над TestPoolEntries думаю.

2017-03-14 08:23 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
>          protected override Action<DomainModel.TestPool> GetEntityInitializer(TestPoolModel model, IEntityQuery query)
Выпилил

2017-03-14 09:38 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                        isSuccessfullyRemoved = true;
Окай, сделал

2017-03-14 09:38 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +            var testPoolEntry = new TestPoolEntryModel();
Мда, переделаю.

2017-03-14 09:39 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            var result = _modelRemover.Remove(testPool);
Может, просто дать Remove на вход не модель, а Id сущности? ему же достаточно этого для понимания, какой объект сущности удалять.

2017-03-14 10:35 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            var result = _modelRemover.Remove(testPool);
Согласен

2017-03-14 19:00 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +            var testPoolEntry = new TestPoolEntryModel();
Удалил, дублирующий метод оказался

2017-03-14 19:00 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            var result = _modelRemover.Remove(testPool);
Сделал

2017-03-17 13:18 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
>                      }
Сделано.

2017-03-27 20:21 UTC, svtz reviewed
@eakarpov, коммит e9b1c4954683bb6bf02c5040aa1793be4ba8b990 какой-то странный.
Написано, что слился с Аниными изменениями, а по сути мержа нету. Замучаемся потом в мастер вливать.
Предлагаю этот коммит удалить (см `git rebase -i`) и сделать честный мержд.
P.S. перед экспериментами советую запушить все изменения.

2017-03-27 20:21 UTC, svtz commented on GraphLabs.DomainModel/GraphLabsDbUpdateException.cs
> +        /// <summary> Ошибка валидации сущности </summary>
комментарий устарел, и ниже тоже

2017-03-27 21:42 UTC, eakarpov commented on GraphLabs.DomainModel/GraphLabsDbUpdateException.cs
> +        /// <summary> Ошибка валидации сущности </summary>
Ну у коммита написано два родителя - мой предыдущий коммит и твой мердж. Разве были пересекающиеся изменения, чтобы нужно было вручную мёрджить что-то? У меня всё автоматически подхватилось.

2017-03-28 04:44 UTC, svtz commented on GraphLabs.DomainModel/GraphLabsDbUpdateException.cs
> +        /// <summary> Ошибка валидации сущности </summary>
Да, всё в порядке. Сорри, на родителей коммита не посмотрел. Предлагаю на будущее оставлять таким коммитам автогенерённые имена "Merge branch ........"

2017-04-10 18:23 UTC, svtz requested changes
Замечания по коду. Предлагаю сосредоточиться на чистке, после чего замёржим.

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Dal.Ef/Repositories/SurveyRepository.cs
> +            return Context.TestQuestions.Where(tq => tq.Question.StartsWith(criteria)).ToArray();
поставишь issue на нормальный поиск? Это чей-нибудь целый уир, в общем-то

2017-04-10 18:23 UTC, svtz commented on GraphLabs.DomainModel/GraphLabsDbUpdateException.cs
> +        /// <summary> Ошибка валидации сущности </summary>
возвращаясь к первому комменту этой беседы.  Глядя на название и использование исключения GraphLabsDbUpdateException, это ведь не только ошибка отсутствия FK. там может быть что угодно, выплюнутое базой!

2017-04-10 18:23 UTC, svtz commented on GraphLabs.DomainModel/Repositories/ISurveyRepository.cs
> +	    TestQuestion[] GetQuestionsSimilarToString(string criteria);
форматирование кривое

2017-04-10 18:23 UTC, svtz commented on GraphLabs.DomainModel/Repositories/ISurveyRepository.cs
> +	    TestQuestion[] GetQuestionsSimilarToString(string criteria);
и комментария нет

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +        public RemovalStatus Remove(long id)
В этом методе хочется несколько иначе делать.
Метод `ExistsInDatabase` не нужен. Нужно сразу по ID попробовать сделать `operation.DataContext.Query.Get<TEntity>(id)`. Если вернулся `null` - то выйти с кодом `RemovalStatus.ElementDoesNotExist`, а иначе - пытаться удалить.

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                        if (e.HResult == -2146233088) // Это код ошибки наличия внешних ключей на данный элемент в базе данных (вроде как)
вот эту проверку я бы встроил в GraphLabsDbUpdateException, и, в зависимости от этого кода, задавал бы в исключение соответствующий message (внутри конструктора GraphLabsDbUpdateException). Сейчас можно поддержать только -2146233088, а на любой другой выдавать "Неизвестная ошибка код XXX"

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +    public interface IEntityBasedModelRemover<in TModel, out TEntity>
кажется, TModel тут уже не нужно.
И это будет IEntityRemover

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelLoader.cs
> +            });
ай жесть какая!
Можно проще:
```csharp
    var array = testPool.TestPoolEntries.Select(a =>
                new TestPoolEntryModel
                {
                    Id = a.Id,
                    Score =  a.Score,
                    ScoringStrategy = a.ScoringStrategy,
                    TestQuestion = a.TestQuestion,
                    TestPool = a.TestPool
                })
        .ToArray();
```

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +        protected override bool ExistsInDatabase(long id)
когда этот метод удалится - AbstractModelRemover можно будет превратить в не-абстрактный EntityRemover, а этот класс - удалить!

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
> +            //});
закомментированный код. Неееееееет!!!! =)

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/AuxTestPoolEntryModel.cs
> +    public class AuxTestPoolEntryModel
Чего-то тут ни одного коммента =(

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/SaveTestPoolEntryModel.cs
> +    public class SaveTestPoolEntryModel : IEntityBasedModel<DomainModel.TestPoolEntry>
Комментов бы!

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/SaveTestPoolEntryModelSaver.cs
> +                //g.TestResults = new List<TestResult>();
закомментированный код!

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +        RemovalStatus Remove(long id);
id в общем случае - object

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelLoader.cs
> +            Contract.Requires(testPoolEntry != null);
Contract.Requires&lt;ArgumentNullException&gt;

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/PreviewController.cs
> +    public class PreviewController : GraphLabsController
Почему весь файл поменялся? LineEnd'инги?

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/QuestionController.cs
> +    public class QuestionController : GraphLabsController
Почему весь файл поменялся? LineEnd'инги?

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/SurveyController.cs
> +    public class QuestionLookForModel
вынести в отдельный файл бы

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/SurveyController.cs
> +        public SurveyController(
в этом файле намешаны табы и пробелы. Нужно сделать только пробелы и привести в порядок форматирование.

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/SurveyController.cs
> +    public class QuestionLookForModel
вынести бы в отдельный класс

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/SurveyController.cs
> +        public SurveyController(
в этом файле смешались пробелы и табы. Нужно оставить только пробелы и привести в порядок форматирование

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/QuestionController.cs
> +    public class QuestionController : GraphLabsController
Почему весь файл изменился? Окончания строк?

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/PreviewController.cs
> +    public class PreviewController : GraphLabsController
Почему весь файл изменился? Окончания строк?

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/SurveyController.cs
> +	        TestQuestion[] questions = _surveyRepository.GetQuestionsSimilarToString(input.Question);
var questions

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/SurveyController.cs
> +            var questionArray = questions.Select(q => new Tuple<string, long>(
можно Tuple.Create(a, b) - так короче

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/SurveyController.cs
> +	        TestQuestion[] questions = _surveyRepository.GetQuestionsSimilarToString(input.Question);
var questions

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                    case "ScoringStrategy":
вместо строк использовать оператор nameof()

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                return Json(false);
а обязательно false возвращать, нельзя просто упасть?

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            if (result == RemovalStatus.Success)
вместо цепочки if-else'ов нужен switch с отдельным кейсом на каждый из 4х вариантов и дефолтным поведением "throw new NotImplementedException()"

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                        break;
тут нужно ошибку кидать "неизвестный тип идите впень"

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                return Json(false);
а обязательно false возвращать, нельзя просто упасть? можно ведь и OutOfMemory так проигнорировать

2017-04-10 18:23 UTC, svtz commented on GraphLabs.DomainModel/Repositories/ISurveyRepository.cs
> +
`Contract.Ensures(Contract.Result<TestQuestion[]>() != null);`

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                        if (e.HResult == -2146233088) // Это код ошибки наличия внешних ключей на данный элемент в базе данных (вроде как)
эту проверку нужно внести вовнутрь GraphLabsDbUpdateException, и задавать message этого исключения в зависимости от этого кода. Сейчас достаточно сделать только для FK, а на остальное присваивать сообщение "неизвестная ошибка код Х"

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +        RemovalStatus Remove(long id);
в общем случае, тип идентификатора - object

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +    public interface IEntityBasedModelRemover<in TModel, out TEntity>
TModel тут больше не нужно. И интерфейс превратится в `IEntityRemover<TEntity>`

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Question/QuestionModelLoader.cs
> +            Contract.Requires(question != null);
`Contract.Requires<ArgumentNullException>(question != null);`

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelLoader.cs
> +            });
Аааа!
Можно проще
```csharp
var array = testPool.TestPoolEntries.Select(a =>
                new TestPoolEntryModel
                {
                    Id = a.Id,
                    Score =  a.Score,
                    ScoringStrategy = a.ScoringStrategy,
                    TestQuestion = a.TestQuestion,
                    TestPool = a.TestPool
                })
         .ToArray();
```

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                if (ExistsInDatabase(id))
тут нужно несколько иначе.
Метод ExistsInDatabase не нужен. вместо этого - сразу делать `operation.DataContext.Query.Get<TEntity>(id)`
Если получили null - возвращать код RemovalStatus.ElementDoesNotExist;
Иначе - пытаться удалить.

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
> +            //});
закомментированная фигня!!!!!!!!

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/AuxTestPoolEntryModel.cs
> +    public class AuxTestPoolEntryModel
комментов бы =(

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/SaveTestPoolEntryModel.cs
> +    public class SaveTestPoolEntryModel : IEntityBasedModel<DomainModel.TestPoolEntry>
комментов бы=)

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/SaveTestPoolEntryModelSaver.cs
> +                //g.TestResults = new List<TestResult>();
что-то закомментировано

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelLoader.cs
> +            Contract.Requires(testPoolEntry != null);
`   Contract.Requires<ArgumentNullException>(testPoolEntry != null);`

2017-04-10 18:23 UTC, svtz commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelRemover.cs
> +    internal sealed class TestPoolEntryModelRemover : AbstractModelRemover<TestPoolEntryModel, DomainModel.TestPoolEntry>
В связи с правками интерфейса, этот класс не нужен.
AbstractModelRemover можно превратить в не-абстрактный EntityRemover.

2017-04-11 19:37 UTC, eakarpov commented on GraphLabs.Dal.Ef/Repositories/SurveyRepository.cs
> +            return Context.TestQuestions.Where(tq => tq.Question.StartsWith(criteria)).ToArray();
Поставил

2017-04-13 16:20 UTC, eakarpov commented on GraphLabs.DomainModel/Repositories/ISurveyRepository.cs
> +
Добавил

2017-04-13 16:22 UTC, eakarpov commented on GraphLabs.DomainModel/Repositories/ISurveyRepository.cs
> +	    TestQuestion[] GetQuestionsSimilarToString(string criteria);
Комментарий добавид. 
@svtz с форматированием не понимаю, что не так... в студии вроде всё ровненько

2017-04-13 16:24 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +        public RemovalStatus Remove(long id)
Переделал

2017-04-13 16:25 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/AbstractModelRemover.cs
> +                if (ExistsInDatabase(id))
см. выше?..

2017-04-13 17:24 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +    public interface IEntityBasedModelRemover<in TModel, out TEntity>
сделал

2017-04-13 17:24 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +    public interface IEntityBasedModelRemover<in TModel, out TEntity>
см. выше

2017-04-13 17:27 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +        RemovalStatus Remove(long id);
поменял

2017-04-13 17:27 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/IEntityBasedModelRemover.cs
> +        RemovalStatus Remove(long id);
см. выше

2017-04-13 17:29 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelLoader.cs
> +            });
заменил

2017-04-13 17:29 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelLoader.cs
> +            });
см. выше

2017-04-13 17:32 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelRemover.cs
> +        protected override bool ExistsInDatabase(long id)
вроде сделал

2017-04-13 17:32 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
> +            //});
удалил

2017-04-13 17:32 UTC, eakarpov commented on GraphLabs.Site.Models/TestPool/TestPoolModelSaver.cs
> +            //});
см. выше

2017-04-13 17:34 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/AuxTestPoolEntryModel.cs
> +    public class AuxTestPoolEntryModel
добавил

2017-04-13 17:35 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/AuxTestPoolEntryModel.cs
> +    public class AuxTestPoolEntryModel
см. выше

2017-04-13 17:36 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/SaveTestPoolEntryModel.cs
> +    public class SaveTestPoolEntryModel : IEntityBasedModel<DomainModel.TestPoolEntry>
добавил..

2017-04-13 17:36 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/SaveTestPoolEntryModelSaver.cs
> +                //g.TestResults = new List<TestResult>();
удалил

2017-04-13 17:36 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/SaveTestPoolEntryModelSaver.cs
> +                //g.TestResults = new List<TestResult>();
см. выше

2017-04-13 17:46 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelLoader.cs
> +            Contract.Requires(testPoolEntry != null);
сделал

2017-04-13 17:46 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelLoader.cs
> +            Contract.Requires(testPoolEntry != null);
см. выше

2017-04-13 17:49 UTC, eakarpov commented on GraphLabs.Site/Controllers/PreviewController.cs
> +    public class PreviewController : GraphLabsController
не знаю... я его вроде вообще не редактировал

2017-04-13 17:57 UTC, eakarpov commented on GraphLabs.Site/Controllers/SurveyController.cs
> +    public class QuestionLookForModel
Вынес

2017-04-13 17:57 UTC, eakarpov commented on GraphLabs.Site/Controllers/SurveyController.cs
> +    public class QuestionLookForModel
см. выше

2017-04-13 17:57 UTC, eakarpov commented on GraphLabs.Site/Controllers/SurveyController.cs
> +	        TestQuestion[] questions = _surveyRepository.GetQuestionsSimilarToString(input.Question);
сделал

2017-04-13 17:57 UTC, eakarpov commented on GraphLabs.Site/Controllers/SurveyController.cs
> +	        TestQuestion[] questions = _surveyRepository.GetQuestionsSimilarToString(input.Question);
сделал

2017-04-13 17:59 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                    case "ScoringStrategy":
вроде сделал - nameof(SaveTestPoolEntryModel.Score)

2017-04-13 18:00 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                        break;
кинул

2017-04-13 21:11 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                return Json(false);
что тогда посылать клиенту при ошибке?

2017-04-13 21:12 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolController.cs
> +            if (result == RemovalStatus.Success)
сделал

2017-04-13 21:13 UTC, eakarpov commented on GraphLabs.Site.Models/Question/QuestionModelLoader.cs
> +            Contract.Requires(question != null);
поменял

2017-04-13 21:22 UTC, eakarpov commented on GraphLabs.Site.Models/TestPoolEntry/TestPoolEntryModelRemover.cs
> +    internal sealed class TestPoolEntryModelRemover : AbstractModelRemover<TestPoolEntryModel, DomainModel.TestPoolEntry>
сделал

2017-04-17 09:30 UTC, eakarpov commented on GraphLabs.DomainModel/GraphLabsDbUpdateException.cs
> +        /// <summary> Ошибка валидации сущности </summary>
Поправил

2017-04-17 09:31 UTC, eakarpov commented on GraphLabs.Site/Controllers/SurveyController.cs
> +        public SurveyController(
Поправил

2017-04-17 09:31 UTC, eakarpov commented on GraphLabs.Site/Controllers/SurveyController.cs
> +        public SurveyController(
См. Выше

2017-04-17 14:43 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                return Json(false);
Поправил. Обрабатываю теперь только конкретные ошибки.

2017-04-17 14:43 UTC, eakarpov commented on GraphLabs.Site/Controllers/TestPoolEntryController.cs
> +                return Json(false);
см. выше

2017-04-18 06:43 UTC, svtz commented on GraphLabs.DomainModel/GraphLabsDbUpdateException.cs
>          public GraphLabsDbUpdateException(string property, string message)
этот ctor удалить надо

2017-04-18 06:43 UTC, svtz commented on GraphLabs.Site.Core/GraphLabsException.cs
> +            this.innerException = innerException;
contrac.requires(ArgumentNullException)(innerException)

2017-04-18 06:43 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/EntityRemover.cs
> +            using (var operation = _operationContextFactory.Create())
contract.requires

2017-04-18 06:43 UTC, svtz commented on GraphLabs.Site.Models/Infrastructure/EntityRemover.cs
> +                    if (e.ExceptionFailure == DbUpgradeFailure.FkViolated)
ExceptionFailure => ErrorCode

2017-04-18 09:46 UTC, eakarpov commented on GraphLabs.DomainModel/GraphLabsDbUpdateException.cs
>          public GraphLabsDbUpdateException(string property, string message)
сделал

2017-04-18 09:47 UTC, eakarpov commented on GraphLabs.Site.Core/GraphLabsException.cs
> +            this.innerException = innerException;
Сделал

2017-04-18 09:48 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/EntityRemover.cs
> +            using (var operation = _operationContextFactory.Create())
Сделал

2017-04-18 09:48 UTC, eakarpov commented on GraphLabs.Site.Models/Infrastructure/EntityRemover.cs
> +                    if (e.ExceptionFailure == DbUpgradeFailure.FkViolated)
Поменял на ExceptionCode

2017-04-21 10:39 UTC, svtz approved these changes

2017-04-21 10:40 UTC, merged