Variant services
GraphLabsSuite/Web pull request #9
Opened 2017-04-26 20:14 UTC by AnnMalofeeva

2017-04-28 15:37 UTC, svtz requested changes

2017-04-28 15:37 UTC, svtz commented on GraphLabs.Site/Views/Labs/Create.cshtml
> +            // я не уверена в правильности параметров
теперь-то уверена? =)

2017-04-28 15:37 UTC, svtz commented on GraphLabs.WcfServices/VariantProviderService.svc.cs
> +                else if ((int)session.User.Role == (int)UserRole.Student)
здесь сделать сравнение без (int), просто `session.User.Role == UserRole.Student`

2017-04-28 18:17 UTC, AnnMalofeeva commented
исправила замечания @svtz

2017-05-16 06:43 UTC, svtz approved these changes

2017-05-16 06:43 UTC, merged